export default [
    {
        id: 100001,
        body: "Oceans are essential to our way of life and central to our planet’s future. And because we are home to the longest coastline in the world, we have a responsibility to protect our oceans and keep them healthy - that’s exactly why we’re joining the Global Ocean Alliance. ",
        date: "June 9 2020",
        likes: 53,
        retweets: 2005,
        hashtags: 'none',
        url: "google.com",
    },
    {
        id: 100001,
        body: "Oceans are essential to our way of life and central to our planet’s future. And because we are home to the longest coastline in the world, we have a responsibility to protect our oceans and keep them healthy - that’s exactly why we’re joining the Global Ocean Alliance. ",
        date: "June 9 2020",
        likes: 53,
        retweets: 2005,
        hashtags: 'none',
        url: "google.com",
    },
    {
        id: 100001,
        body: "Oceans are essential to our way of life and central to our planet’s future. And because we are home to the longest coastline in the world, we have a responsibility to protect our oceans and keep them healthy - that’s exactly why we’re joining the Global Ocean Alliance. ",
        date: "June 9 2020",
        likes: 53,
        retweets: 2005,
        hashtags: 'none',
        url: "google.com",
    },
    {
        id: 100001,
        body: "Oceans are essential to our way of life and central to our planet’s future. And because we are home to the longest coastline in the world, we have a responsibility to protect our oceans and keep them healthy - that’s exactly why we’re joining the Global Ocean Alliance. ",
        date: "June 9 2020",
        likes: 53,
        retweets: 2005,
        hashtags: 'none',
        url: "google.com",
    },
    {
        id: 100001,
        body: "Oceans are essential to our way of life and central to our planet’s future. And because we are home to the longest coastline in the world, we have a responsibility to protect our oceans and keep them healthy - that’s exactly why we’re joining the Global Ocean Alliance. ",
        date: "June 9 2020",
        likes: 53,
        retweets: 2005,
        hashtags: 'none',
        url: "google.com",
    },
    {
        id: 100001,
        body: "Oceans are essential to our way of life and central to our planet’s future. And because we are home to the longest coastline in the world, we have a responsibility to protect our oceans and keep them healthy - that’s exactly why we’re joining the Global Ocean Alliance. ",
        date: "June 9 2020",
        likes: 53,
        retweets: 2005,
        hashtags: 'none',
        url: "google.com",
    },
];